const lang = {
    "en": {
        "server": "Server",
        "website": "Website",
        "username": "Username",
        "email": "Email",
        "password": "Password",
        "signin": "Sign in",
        "signup": "Sign up",
        "signout": "Sign out",
        "okay": "Okay",
        "add": "Add",
        "change": "Change",
        "use": "Use",
        "copy": "Copy",
        "cancel": "Cancel",
        "try_again": "Try again",
        "success": "SUCCESS",
        "error": "ERROR",
        "delete": "Delete",
        "import": "Import",
        "import_from": "Import from {name}",
        "import_invalid": "Data in import is invalid!",
        "import_success": "{success_number} passwords has been successfully imported!",
        "import_errors": "{success_number} passwords has been successfully imported, but {error_number} passwords has not been imported!",
        "backup": "Backup",
        "export": "Export",
        "passwords": "Passwords",
        "import_export": "Import & Export",
        "theme": "Theme",
        "search": "Search",
        "length": "Length",
        "add_password": "Add password",
        "add_password_success": "Password has been added successfully",
        "change_password_success": "Password has been changed successfully",
        "remove_password_success": "Password has been removed successfully",
        "edit_password": "Edit password",
        "password_generator": "Password Generator",
        "delete_password": "Delete password",
        "delete_password_confirmation": "Are you sure you want to delete your password? Your password will be permanently removed from server forever. This action cannot be undone.",
        "delete_account": "Delete account",
        "delete_account_info": "Once you delete your account, you will lose all data associated with it.",
        "delete_account_confirmation": "Are you sure you want to delete your account? All of your data will be permanently removed from server forever. This action cannot be undone.",
        "url_invalid": "Server url is invalid!",
        "server_unreachable": "Server is unreachable!",
        "registration_completed": "Registration is completed!",
        "dont_have_account_link": "Don't have account yet? Sign up here.",
        "already_have_account_link": "Already have account? Sign in here.",
        "username_validation": "Username must be between 3 and 255 character long and can't contain spaces!",
        "username_validation2": "Username can't contains provided special characters: ' \" \\",
        "password_validation": "Password must be between 8 and 255 character long and can't contain spaces!",
        "password_validation2": "Password can't contains provided special characters: ' \" \\",
        "website_validation": "Website much be between 5 and 255 character long and can't contain spaces!",
        "website_validation2": "Website can't contains provided special characters: ' \" \\"
    },
    "nl": {
        "server": "Server",
        "website": "Website",
        "username": "Gebruikersnaam",
        "email": "Email",
        "password": "Wachtwoord",
        "signin": "Inloggen",
        "signup": "Aanmelden",
        "signout": "Afmelden",
        "okay": "Ok",
        "add": "Toevoegen",
        "change": "Wijzigen",
        "use": "Gebruiken",
        "copy": "Kopiëren",
        "cancel": "Annuleren",
        "try_again": "Probeer opnieuw",
        "success": "Geslaagd",
        "error": "Foutmelding",
        "delete": "Verwijderen",
        "import": "Importeren",
        "import_from": "Importeren van {name}",
        "import_invalid": "Data import is ongeldig!",
        "import_success": "{success_number} wachtwoorden zijn succesvol geïmporteerd!",
        "import_errors": "{success_number} wachtwoorden zijn succesvol geimporteerd, {error_number} wachtworden zijn niet geïmporteerd!",
        "backup": "Backup",
        "export": "Exporteren",
        "passwords": "Wachtwoorden",
        "import_export": "Importeren & Exporteren",
        "theme": "Thema",
        "search": "Zoeken",
        "length": "Lengte",
        "add_password": "Wachtwoorden toevoegen",
        "add_password_success": "Wachtwoord succesvol toegevoegd",
        "change_password_success": "Wachtwoord succesvol gewijzigd",
        "remove_password_success": "Wachtwoord succesvol verwijderd",
        "edit_password": "Wachtwood bewerken",
        "password_generator": "Wachtwoorden Generator",
        "delete_password": "Wachtwoord verwijderen",
        "delete_password_confirmation": "Weet je het zeker dat je het wachtwoord wil verwijderen? Je wachtwoord wordt permanent verwijderd, dit kan niet ongedaan gemaakt worden.",
        "delete_account": "Verwijder account",
        "delete_account_info": "Je account verwijderd, alle gekoppelde data en wachtwoorden worden verwijderd.",
        "delete_account_confirmation": "Weet je zeker dat je je account wil verwijderen? Al je data wordt verwijderd. Deze actie kan niet ongedaan gemaakt worden!",
        "url_invalid": "Server url is ongeldig!",
        "server_unreachable": "Server is niet bereikbaar!",
        "registration_completed": "Registratie is voltooid!",
        "dont_have_account_link": "Nog geen account? Hier inschrijven.",
        "already_have_account_link": "Heb je al een account? Hier aanmelden.",
        "username_validation": "Gebruikersnaam moet minimaal 3 en maximaal 255 karakters zijn en mag geen spaties bevatten!",
        "username_validation2": "Gebruikersnaam kan niet de volgende speciale karakters bevatten: ' \" \\",
        "password_validation": "Wachtwoord moet minimaal 8 en maximaal 255 karakters zijn en mag geen spaties bevatten!",
        "password_validation2": "Wachtwoord kan niet de volgende speciale karakters bevatten: ' \" \\",
        "website_validation": "Website moet minimaal 5 en maximaal 255 karakters zijn en mag geen spaties bevatten!",
        "website_validation2": "Website kan niet de volgende speciale karakters bevatten: ' \" \\"
    },
    "sl": {
        "server": "Strežnik",
        "website": "Spletna stran",
        "username": "Uporabniško ime",
        "email": "E-naslov",
        "password": "Geslo",
        "signin": "Vpis",
        "signup": "Prijava",
        "signout": "Odjava",
        "okay": "Okay",
        "add": "Dodaj",
        "change": "Spremeni",
        "use": "Uporabi",
        "copy": "Kopiraj",
        "cancel": "Prekliči",
        "try_again": "Poskusite znova",
        "success": "USPEH",
        "error": "NAPAKA",
        "delete": "Izbriši",
        "import": "Uvozi",
        "import_from": "Uvozi iz {name}",
        "import_invalid": "Podatki pri uvozu so neveljavni!",
        "import_success": "{success_number} gesla so bila uspešno uvožena! ",
        "import_errors": "{success_number} gesel je bilo uspešno uvoženih, {error_number} gesel pa ni bilo uvoženih!",
        "backup": "Rezerva",
        "export": "Izvoz",
        "passwords": "Gesla",
        "import_export": "Uvoz in Izvoz",
        "theme": "Tema",
        "search": "Iskanje",
        "length": "Dolžina",
        "add_password": "Dodaj geslo",
        "add_password_success": "Geslo je bilo uspešno dodano",
        "change_password_success": "Geslo je bilo uspešno spremenjeno",
        "remove_password_success": "Geslo je bilo uspešno odstranjeno",
        "edit_password": "Uredi geslo",
        "password_generator": "Generator gesel",
        "delete_password": "Izbriši geslo",
        "delete_password_confirmation": "Ali ste prepričani, da želite izbrisati geslo? Vaše geslo bo za vedno odstranjeno s strežnika. Tega dejanja ni mogoče razveljaviti.",
        "delete_account": "Izbriši račun",
        "delete_account_info": "Ko izbrišete račun, boste izgubili vse podatke, povezane z njim.",
        "delete_account_confirmation": "Ali ste prepričani, da želite izbrisati svoj račun? Vsi vaši podatki bodo za vedno odstranjeni s strežnika. Tega dejanja ni mogoče razveljaviti.",
        "url_invalid": "URL strežnika ni veljaven!",
        "server_unreachable": "Strežnik je nedosegljiv!",
        "registration_completed": "Registracija je končana!",
        "dont_have_account_link": "Še nimate računa? Prijavite se tukaj.",
        "already_have_account_link": "Že imate račun? Prijavite se tukaj.",
        "username_validation": "Uporabniško ime mora biti dolgo med 3 in 255 znaki in ne sme vsebovati presledkov!",
        "username_validation2": "Uporabniško ime ne more vsebovati predvidenih posebnih znakov: ' \" \\",
        "password_validation": "Geslo mora biti dolgo med 8 in 255 znaki in ne sme vsebovati presledkov!",
        "password_validation2": "Geslo ne more vsebovati predvidenih posebnih znakov: ' \" \\",
        "website_validation": "Spletno mesto mora biti dolgo med 5 in 255 znaki in ne sme vsebovati presledkov!",
        "website_validation2": "Spletno mesto ne more vsebovati predvidenih posebnih znakov: ' \" \\"
    }
}

const errors = {
    "en": {
        "0": "Successful",
        "1": "Username is invalid!",
        "2": "Password is incorrect!",
        "3": "Something went wrong while inserting data to database!",
        "4": "Username is already registered!",
        "5": "Password must be between 8 and 255 characters long and have at least one letter, one number and one special character!",
        "6": "Email is invalid!",
        "7": "Username doesn't exist!",
        "8": "You don't have any saved password.",
        "9": "Domain is invalid!",
        "10": "User does not own this password!",
        "11": "Something went wrong while deleting data from database!",
        "12": "Username must be between 6 and 30 characters long and can only contains letters, numbers and dots!",
        "13": "Something went wrong while updating data in database!",
        "14": "Json is invalid!",
        "15": "This server can't accept more users!",
        "16": "You have reached maximum amount of stored passwords!",
        "400": "Action was not provided in POST!",
        "401": "Action is invalid!",
        "403": "You didn't provide all required values in POST.",
        "404": "Can't connect into API.",
        "429": "You are sending too many requests! Please wait some time before executing this action.",
        "505": "Something went wrong while connecting to database!",
        "999": "You don't have permission to use this endpoint."
    },
    "nl": {
        "0": "Voltooid",
        "1": "Gebruikersnaam is ongeldig!",
        "2": "Wachtwoord is ongeldig!",
        "3": "Er is iets fout gegaan bij het schrijven naar de database!",
        "4": "Gebruikersnaam is al in gebruik!",
        "5": "Gebruikersnaam moet minimaal 8 en maximaal 255 karakters zijn, minimaal één letter, één cijfer en één speciaal karakter bevatten!",
        "6": "Email is ongeldig!",
        "7": "Gebruikersnaam bestaat niet!",
        "8": "Er is geen wachtwoord opgeslagen.",
        "9": "Domein is ongeldig!",
        "10": "Gebruiker heeft dit wachtwoord niet!",
        "11": "Er is iets fout gegaan bij het verwijderen uit de database!",
        "12": "Gebruikersnaam moet minimaal 6 en maximaal 30 karakters zijn en kan alleen letters, nummers en punten bevatten!",
        "13": "Er is iets fout gegaan bij het bijwerken van de database!",
        "14": "Json is ongeldig!",
        "15": "De server heeft het maximale aantal gebruikers bereikt!",
        "16": "Je hebt het maximale aantal wachtwoorden bereikt!",
        "400": "Actie was niet aangegeven in POST!",
        "401": "Actie is ongeldig!",
        "403": "Je hebt niet alle verplicte velden ingevuld in POST.",
        "404": "Kan niet verbinden met API.",
        "429": "Je stuurt teveel verzoeken! Wacht even voor het uitvoeren van deze actie.",
        "505": "Er ging iets fout bij het verbinden met de database!",
        "999": "Je hebt geen rechten om te verbinden met dit eindpunt."
    },
    "sl": {
        "0": "Uspešno",
        "1": "Uporabniško ime je neveljavno!",
        "2": "Geslo je napačno!",
        "3": "Med vstavljanjem podatkov v bazo podatkov je prišlo do napake!",
        "4": "Uporabniško ime je že registrirano!",
        "5": "Geslo mora biti dolgo med 8 in 255 znaki in mora vsebovati vsaj eno črko, eno številko in en poseben znak!",
        "6": "E-pošta je neveljavna!",
        "7": "Uporabniško ime ne obstaja!",
        "8": "Nimate shranjenega gesla.",
        "9": "Domena je neveljavna!",
        "10": "Uporabnik ni lastnik tega gesla!",
        "11": "Med brisanjem podatkov iz baze podatkov je prišlo do napake!",
        "12": "Uporabniško ime mora biti dolgo med 6 in 30 znakov in lahko vsebuje samo črke, številke in pike!",
        "13": "Med posodabljanjem podatkov v bazi je prišlo do napake!",
        "14": "Json je neveljaven!",
        "15": "Ta strežnik ne more sprejeti več uporabnikov!",
        "16": "Dosegli ste največjo količino shranjenih gesel!",
        "400": "Akcija ni bila zagotovljena v POST-u!",
        "401": "Dejanje je neveljavno!",
        "403": "V POST niste navedli vseh zahtevanih vrednosti. ",
        "404": "Ne morem se povezati z API-jem.",
        "429": "Pošiljate preveč zahtev! Počakajte nekaj časa, preden izvedete to dejanje. ",
        "505": "Med povezovanjem z bazo podatkov je prišlo do napake!",
        "999": "Nimate dovoljenja za uporabo te točke."
    }
}