const lang = {
    "en": {
        "server": "Server",
        "website": "Website",
        "username": "Username",
        "email": "Email",
        "password": "Password",
        "signin": "Sign in",
        "signup": "Sign up",
        "signout": "Sign out",
        "okay": "Okay",
        "add": "Add",
        "change": "Change",
        "use": "Use",
        "copy": "Copy",
        "cancel": "Cancel",
        "try_again": "Try again",
        "success": "SUCCESS",
        "error": "ERROR",
        "delete": "Delete",
        "import": "Import",
        "import_from": "Import from {name}",
        "import_invalid": "The data in your import is invalid!",
        "import_success": "{success_number} passwords imported successfully!",
        "import_errors": "{success_number} passwords imported successfully, but {error_number} passwords NOT imported!",
        "backup": "Backup",
        "export": "Export",
        "passwords": "Passwords",
        "import_export": "Import & Export",
        "theme": "Theme",
        "search": "Search",
        "length": "Length",
        "add_password": "Add password",
        "add_password_success": "Password has been added successfully",
        "change_password_success": "Password has been changed successfully",
        "remove_password_success": "Password has been removed successfully",
        "edit_password": "Change password",
        "password_generator": "Generate password",
        "delete_password": "Delete password",
        "delete_password_confirmation": "Are you sure you want to delete your password? Your password will be permanently removed from the server. This action can NOT be undone.",
        "delete_account": "Delete account",
        "delete_account_info": "Once you delete your account, you will lose all data associated with it.",
        "delete_account_confirmation": "Are you sure you want to delete your account? All of your data will be permanently removed from the server. This action can NOT be undone.",
        "url_invalid": "Server url is invalid!",
        "server_unreachable": "Server is unreachable!",
        "registration_completed": "Registration is completed!",
        "dont_have_account_link": "Don't have an account yet? Sign up here.",
        "already_have_account_link": "Already registered? Sign in here.",
        "username_validation": "Username should be between 3 to 255 characters long and can not contain any spaces!",
        "username_validation2": "Username may not contain the following special characters: ' \" \\",
        "password_validation": "Password should be from 8 to 255 characters long and can not contain any spaces!",
        "password_validation2": "Password may not contain provided special characters: ' \" \\",
        "website_validation": "Website should be from 5 to 255 characters long, and must not have any spaces!",
        "website_validation2": "Website may not contain the following special characters: ' \" \\"
    },
    "zh-CN": {
        "server": "服务器",
        "website": "网站",
        "username": "用户名",
        "email": "邮箱",
        "password": "密码",
        "signin": "登录",
        "signup": "注册",
        "signout": "登出",
        "okay": "好的",
        "add": "添加",
        "change": "修改",
        "use": "使用",
        "copy": "复制",
        "cancel": "取消",
        "try_again": "重试",
        "success": "成功",
        "error": "错误",
        "delete": "删除",
        "import": "导入",
        "import_from": "从 {name} 中导入",
        "import_invalid": "导入的数据不合法！",
        "import_success": "成功导入了 {success_number} 个密码！",
        "import_errors": "成功导入了 {success_number} 个密码，还有 {error_number} 个密码导入失败！",
        "backup": "备份",
        "export": "导出",
        "passwords": "密码",
        "import_export": "导入 & 导出",
        "theme": "主题",
        "search": "搜索",
        "length": "长度",
        "add_password": "添加密码",
        "add_password_success": "密码添加成功",
        "change_password_success": "密码修改成功",
        "remove_password_success": "密码移除成功",
        "edit_password": "修改密码",
        "password_generator": "生成密码",
        "delete_password": "删除密码",
        "delete_password_confirmation": "您确定要删除密码吗？ 您的密码将从服务器中永久删除，此操作无法撤消。",
        "delete_account": "删除账户",
        "delete_account_info": "删除帐户后，您将丢失与其关联的所有数据",
        "delete_account_confirmation": "您确定要删除您的帐户吗？ 您的所有数据都将从服务器中永久删除，此操作无法撤消。",
        "url_invalid": "服务器URL不合法！",
        "server_unreachable": "服务器无法访问！",
        "registration_completed": "注册完成！",
        "dont_have_account_link": "还没有账号？在这里注册",
        "already_have_account_link": "已经注册了？在这里登录",
        "username_validation": "用户名的长度应在 3 到 255 个字符之间，并且不能包含任何空格！",
        "username_validation2": "用户名不得包含以下特殊字符：' \" \\",
        "password_validation": "密码长度为 8 到 255 个字符，不能包含任何空格！",
        "password_validation2": "密码不能包含提供的特殊字符：' \" \\",
        "website_validation": "网站长度应为 5 到 255 个字符，且不得有任何空格！",
        "website_validation2": "网站不得包含以下特殊字符：' \" \\"
    },
    "hi": {
        "server": "सर्वर",
        "website": "वेबसाइट",
        "username": "उपयोगकर्ता नाम",
        "email": "ईमेल",
        "password": "कुंजिका",
        "signin": "साइन इन करें",
        "signup": "साइन अप करें",
        "signout": "प्रस्थान करें",
        "okay": "ठीक",
        "add": "जोड़ें",
        "change": "परिवर्तन",
        "use": "उपयोग",
        "copy": "प्रतिलिपि",
        "cancel": "रद्द करना",
        "try_again": "पुनः प्रयास करें",
        "success": "सफलता",
        "error": "एरर",
        "delete": "हटाएं",
        "import": "आयात",
        "import_from": "लाया गया",
        "import_invalid": "आपके आयात का डेटा अमान्य है!",
        "import_success": "{success_number} पासवर्ड सफलतापूर्वक आयात किए गए!",
        "import_errors": "{success_number} पासवर्ड सफलतापूर्वक आयात किए गए, लेकिन {error_number} पासवर्ड आयात नहीं किया गया!",
        "backup": "बैकअप",
        "export": "निर्यात",
        "passwords": "कुंजिका",
        "import_export": "आयात तथा निर्यात",
        "theme": "विषय",
        "search": "खोज",
        "length": "लंबाई",
        "add_password": "पासवर्ड जोड़ें",
        "add_password_success": "पासवर्ड सफलतापूर्वक जोड़ दिया गया है",
        "change_password_success": "पासवर्ड सफलतापूर्वक बदल दिया गया है",
        "remove_password_success": "पासवर्ड सफलतापूर्वक हटा दिया गया है",
        "edit_password": "पासवर्ड बदलें",
        "password_generator": "पासवर्ड उत्पन्न करें",
        "delete_password": "पासवर्ड हटाएं",
        "delete_password_confirmation": "क्या आप वाकई अपना पासवर्ड हटाना चाहते हैं? आपका पासवर्ड सर्वर से स्थायी रूप से हटा दिया जाएगा। इस एक्शन को वापस नहीं किया जा सकता।",
        "delete_account": "खाता हटा दो",
        "delete_account_info": "एक बार जब आप अपना खाता हटा देते हैं, तो आप इससे संबद्ध सभी डेटा खो देंगे।",
        "delete_account_confirmation": "क्या आप इस खाते को हटाने के लिए सुनिश्चित हैं? आपका सारा डेटा सर्वर से स्थायी रूप से हटा दिया जाएगा। इस एक्शन को वापस नहीं किया जा सकता।",
        "url_invalid": "सर्वर यूआरएल अमान्य है!",
        "server_unreachable": "सर्वर पहुंच योग्य नहीं है!",
        "registration_completed": "पंजीकरण पूरा हो गया है!",
        "dont_have_account_link": "अब तक कोई खाता नहीं है? पंजी यहॉ करे।",
        "already_have_account_link": "पहले से ही पंजीकृत? यहां साइन इन करो।",
        "username_validation": "उपयोगकर्ता नाम 3 से 255 वर्णों के बीच होना चाहिए और इसमें कोई रिक्त स्थान नहीं होना चाहिए!",
        "username_validation2": "उपयोगकर्ता नाम में निम्नलिखित विशेष वर्ण नहीं हो सकते हैं: ' \" \\",
        "password_validation": "पासवर्ड 8 से 255 वर्णों का होना चाहिए और इसमें कोई स्थान नहीं होना चाहिए!",
        "password_validation2": "पासवर्ड में विशेष वर्ण शामिल नहीं हो सकते हैं: ' \" \\",
        "website_validation": "वेबसाइट 5 से 255 वर्णों तक लंबी होनी चाहिए, और इसमें कोई स्थान नहीं होना चाहिए!",
        "website_validation2": "वेबसाइट में निम्नलिखित विशेष वर्ण नहीं हो सकते हैं: ' \" \\"
    },
    "fr": {
        "server": "Serveur",
        "website": "Site web",
        "username": "Pseudo",
        "email": "Email",
        "password": "Mot de passe",
        "signin": "Connection",
        "signup": "Inscription",
        "signout": "Déconnection",
        "okay": "Ok",
        "add": "Ajouter",
        "change": "Changer",
        "use": "Utiliser",
        "copy": "Copier",
        "cancel": "Annuler",
        "try_again": "Réessayer",
        "success": "RÉUSSITE",
        "error": "ERREUR",
        "delete": "Supprimer",
        "import": "Importer",
        "import_from": "Importer depuis {name}",
        "import_invalid": "Les données de l'import sont invalides !",
        "import_success": "{success_number} mots de passe importés !",
        "import_errors": "{success_number} mots de passe importés, {error_number} mots de passe non importés !",
        "backup": "Sauvegarde",
        "export": "Exporter",
        "passwords": "Mots de passe",
        "import_export": "Importer et exporter",
        "theme": "Thème",
        "search": "Recherche",
        "length": "Longueur",
        "add_password": "Ajouter un mot de passe",
        "add_password_success": "Mot de passe ajouté avec succès",
        "change_password_success": "Mot de passe changé avec succès",
        "remove_password_success": "Mot de passe supprimé avec succès",
        "edit_password": "Modifier le mot de passe",
        "password_generator": "Générer un mot de passe",
        "delete_password": "Supprimer un mot de passe",
        "delete_password_confirmation": "Voulez-vous vraiment supprimer ce mot de passe ? Il sera retiré du serveur pour toujours. Cette action ne peut PAS être annulée.",
        "delete_account": "Supprimer le compte",
        "delete_account_info": "Une fois que vous supprimez votre compte, vous allez perdre toutes les informations le concernant.",
        "delete_account_confirmation": "Êtes vous sûr de vouloir supprimer votre compte ? Toutes vos données seront supprimées du serveur. Cette action ne peut PAS être annulée.",
        "url_invalid": "L'URL du serveur est invalide !",
        "server_unreachable": "Le serveur ne peut pas être contacté !",
        "registration_completed": "Inscription terminée !",
        "dont_have_account_link": "Pas encore de compte ? Inscrivez vous ici.",
        "already_have_account_link": "Vous avez déjà un compte ? Connectez-vous ici.",
        "username_validation": "Le pseudo doit faire entre 3 et 255 caractères et ne doit pas contenir d'espaces !",
        "username_validation2": "Le pseudo ne doit pas contenir les caractères suivants : ' \" \\",
        "password_validation": "Le mot de passe doit faire entre 8 et 255 caractères et ne doit pas contenir d'espaces !",
        "password_validation2": "Le mot de passe ne doit pas contenir les caractères suivants : ' \" \\",
        "website_validation": "Le site web doit faire entre 5 et 255 caractères et ne doit pas contenir d'espaces !",
        "website_validation2": "L'URL du site web ne doit pas contenir les caractères suivants : ' \" \\"
    },
    "ru": {
        "server": "Сервер",
        "website": "Вебсайт",
        "username": "Никнейм",
        "email": "Почта",
        "password": "Пароль",
        "signin": "Войти",
        "signup": "Выйти",
        "signout": "Выход",
        "okay": "Ок",
        "add": "Добавить",
        "change": "Изменить",
        "use": "Использовать",
        "copy": "Скопировать",
        "cancel": "Отменить",
        "try_again": "Попробуйте ещё раз",
        "success": "ВЫПОЛНЕНО",
        "error": "ОШИБКА",
        "delete": "Удалить",
        "import": "Импортировать",
        "import_from": "Импортировать из {name}",
        "import_invalid": "Данные в вашем импорте недействительны!",
        "import_success": "{success_number} пароли успешно импортированы!",
        "import_errors": "{success_number} паролей успешно импортировано, но {error_number} не импортированы!",
        "backup": "Резервное копирование",
        "export": "Экспорт",
        "passwords": "Пароли",
        "import_export": "Импорт и Экспорт",
        "theme": "Тема",
        "search": "Поиск",
        "length": "Размер",
        "add_password": "Добавить пароль",
        "add_password_success": "Пароль был успешно добавлен",
        "change_password_success": "Пароль успешно изменен",
        "remove_password_success": "Пароль успешно удален",
        "edit_password": "Пароль успешно изменён",
        "password_generator": "Сгенерировать пароль",
        "delete_password": "Удалить пароль",
        "delete_password_confirmation": "Вы уверены, что хотите удалить свой пароль? Ваш пароль будет навсегда удален! Вы не сможете его вернуть.",
        "delete_account": "Удалить аккаунт",
        "delete_account_info": "После удаления аккаунта вы потеряете все связанные с ним аккаунты.",
        "delete_account_confirmation": "Вы уверены, что хотите удалить свой аккаунт? Вы не сможете это отмнеить.",
        "url_invalid": "URL-адрес сервера недействителен!",
        "server_unreachable": "Сервер недоступен!",
        "registration_completed": "Регистрация завершена!",
        "dont_have_account_link": "Еще нет учетной записи? Зарегистрируйтесь.",
        "already_have_account_link": "Уже зарегистрирован? Войдите.",
        "username_validation": "Имя пользователя должно содержать от 3 до 255 символов и не может содержать пробелы!",
        "username_validation2": "Имя пользователя не может содержать символы: ' \" \\",
        "password_validation": "Пароль должен содержать от 8 до 255 символов и не может содержать пробелов!",
        "password_validation2": "Пароль не может содержать символы: ' \" \\",
        "website_validation": "Веб-сайт должен содержать от 5 до 255 символов и не должен содержать пробелы!",
        "website_validation2": "Веб-сайт не может содержать символы: ' \" \\"
    },
    "de": {
        "server": "Server",
        "website": "Webseite",
        "username": "Nutzername",
        "email": "Email",
        "password": "Passwort",
        "signin": "Anmelden",
        "signup": "Anmelden",
        "signout": "Abmelden",
        "okay": "Okay",
        "add": "Hinzufügen",
        "change": "änderung",
        "use": "benutzen",
        "copy": "Kopieren",
        "cancel": "Abbrechen",
        "try_again": "Versuchen Sie es erneut",
        "success": "ERFOLG",
        "error": "FEHLER",
        "delete": "Löschen",
        "import": "Importieren",
        "import_from": "Importieren von {name}",
        "import_invalid": "Daten beim Import sind ungültig!",
        "import_success": "{success_number} passwörter wurden erfolgreich importiert!",
        "import_errors": "{success_number} passwörter wurden erfolgreich importiert, aber {error_number} Passwörter wurden nicht importiert!",
        "backup": "Backup",
        "export": "Exportieren",
        "passwords": "Passwörter",
        "import_export": "Import & Export",
        "theme": "Thema",
        "search": "Suche",
        "length": "Länge",
        "add_password": "Passwort hinzufügen",
        "add_password_success": "Passwort wurde erfolgreich hinzugefügt",
        "change_password_success": "Passwort wurde erfolgreich geändert",
        "remove_password_success": "Passwort wurde erfolgreich entfernt",
        "edit_password": "Passwort bearbeiten",
        "password_generator": "Passwort Generator",
        "delete_password": "Passwort löschen",
        "delete_password_confirmation": "Sind Sie sicher, dass Sie Ihr Passwort löschen möchten? Ihr Passwort wird für immer vom Server entfernt. Diese Aktion kann nicht rückgängig gemacht werden.",
        "delete_account": "Konto löschen",
        "delete_account_info": "Sobald Sie Ihr Konto löschen, verlieren Sie alle damit verbundenen Daten.",
        "delete_account_confirmation": "Sind Sie sicher, dass Sie Ihr Konto löschen möchten? Alle Ihre Daten werden für immer vom Server entfernt. Diese Aktion kann nicht rückgängig gemacht werden.",
        "url_invalid": "Server-URL ist ungültig!",
        "server_unreachable": "Server ist nicht erreichbar!",
        "registration_completed": "Registrierung ist abgeschlossen!",
        "dont_have_account_link": "Sie haben noch kein Konto? Melden Sie sich hier an.",
        "already_have_account_link": "Sie haben bereits ein Konto? Melden Sie sich hier an.",
        "username_validation": "Der Benutzername muss zwischen 3 und 255 Zeichen lang sein und darf keine Leerzeichen enthalten!",
        "username_validation2": "Benutzername darf keine angegebenen Sonderzeichen enthalten: ' \" \\",
        "password_validation": "Passwort muss zwischen 8 und 255 Zeichen lang sein und darf keine Leerzeichen enthalten!",
        "password_validation2": "Passwort darf keine angegebenen Sonderzeichen enthalten: ' \" \\",
        "website_validation": "Website kann zwischen 5 und 255 Zeichen lang sein und darf keine Leerzeichen enthalten!",
        "website_validation2": "Website darf keine angegebenen Sonderzeichen enthalten: ' \" \\"
    },
    "it": {
        "server": "Server",
        "website": "Sito web",
        "username": "Nome utente",
        "email": "Email",
        "password": "Password",
        "signin": "Entra",
        "signup": "Registrati",
        "signout": "Esci",
        "okay": "Okay",
        "add": "Aggiungi",
        "change": "Modifica",
        "use": "Usa",
        "copy": "Copia",
        "cancel": "Annulla",
        "try_again": "Riprova",
        "success": "SUCCESSO",
        "error": "ERRORE",
        "delete": "Elimina",
        "import": "Importa",
        "import_from": "Importa da {name}",
        "import_invalid": "I dati importati non sono validi!",
        "import_success": "{success_number} password importate correttamente!",
        "import_errors": "{success_number} password sono state importate correttamente, ma {error_number} password NON sono state importate!",
        "backup": "Backup",
        "export": "Esporta",
        "passwords": "Password",
        "import_export": "Importa & Esporta",
        "theme": "Tema",
        "search": "Cerca",
        "length": "Lunghezza",
        "add_password": "Aggiungi password",
        "add_password_success": "La password è stata salvata correttamente",
        "change_password_success": "La password è stata modificata correttamente",
        "remove_password_success": "La password è stata eliminata correttamente",
        "edit_password": "Modifica password",
        "password_generator": "Genera password",
        "delete_password": "Elimina password",
        "delete_password_confirmation": "Siete sicuri di voler eliminare la vostra password? La password sarà permanentemente rimossa dal server. Questa azione non può essere annullata.",
        "delete_account": "Elimina account",
        "delete_account_info": "Una volta eliminato l'account, perderete tutti i dati ad esso associati.",
        "delete_account_confirmation": "Siete sicuri di voler eliminare il vostro account? Tutti i vostri dati saranno permanentemente rimossi dal server. Questa azione non può essere annullata.",
        "url_invalid": "URL del server non valido!",
        "server_unreachable": "Il server non è raggiungibile!",
        "registration_completed": "Registrazione completata!",
        "dont_have_account_link": "Non hai un account? Registrati qui.",
        "already_have_account_link": "Hai già effettuato la registrazione? Entra qui.",
        "username_validation": "Il nome utente deve essere compreso tra i 3 e i 255 caratteri e non può contenere spazi!",
        "username_validation2": "Il nome utente non può contenere i seguenti caratteri speciali: ' \" \\",
        "password_validation": "La password deve essere compresa tra gli 8 e i 255 caratteri e non può contenere spazi!",
        "password_validation2": "La password non può contenere i seguenti caratteri speciali: ' \" \\",
        "website_validation": "L'indirizzo deve essere compreso tra gli 8 e i 255 caratteri e non può contenere spazi!",
        "website_validation2": "L'indirizzo non può contenere i seguenti caratteri speciali: ' \" \\"
    },
    "pl": {
        "server": "Serwer",
        "website": "Domena",
        "username": "Nazwa użytkownika",
        "email": "E-mail",
        "password": "Hasło",
        "signin": "Zaloguj się",
        "signup": "Zarejestruj się",
        "signout": "Wyloguj",
        "okay": "OK",
        "add": "Dodaj",
        "change": "Zmień",
        "use": "Użyj",
        "copy": "Kopiuj",
        "cancel": "Anuluj",
        "try_again": "Spróbuj ponownie",
        "success": "SUKCES",
        "error": "BŁĄD",
        "delete": "Usuń",
        "import": "Importuj",
        "import_from": "Importuj z {name}",
        "import_invalid": "Importowane dane są nieprawidłowe!",
        "import_success": "Pomyślnie zaimportowano {success_number} haseł!",
        "import_errors": "Pomyślnie zaimportowano {success_number} haseł, {error_number} haseł NIE udało się zaimportować!",
        "backup": "Utwórz kopię zapasową",
        "export": "Eksportuj",
        "passwords": "Hasła",
        "import_export": "Importuj i Eksportuj",
        "theme": "Motyw",
        "search": "Szukaj",
        "length": "Długość",
        "add_password": "Dodaj hasło",
        "add_password_success": "Hasło zostało dodane pomyślnie",
        "change_password_success": "Hasło zostało zmienione pomyślnie",
        "remove_password_success": "Hasło zostało usunięte pomyślnie",
        "edit_password": "Zmień hasło",
        "password_generator": "Wygeneruj hasło",
        "delete_password": "Usuń hasło",
        "delete_password_confirmation": "Czy masz pewność, że chcesz usunąć swoje hasło? Twoje hasło zostanie trwale usunięte z serwera. Tej akcji NIE można cofnąć.",
        "delete_account": "Usuń konto",
        "delete_account_info": "Po usunięciu konta stracisz wszystkie powiązane z nim dane.",
        "delete_account_confirmation": "Czy masz pewność, że chcesz usunąć swoje konto? Wszystkie Twoje dane zostaną trwale usunięte z serwera. Tej akcji NIE można cofnąć.",
        "url_invalid": "Nieprawidłowy adres URL serwera!",
        "server_unreachable": "Nie można połączyć się z serwerem!",
        "registration_completed": "Rejestracja została pomyślnie zakończona!",
        "dont_have_account_link": "Nie masz jeszcze konta? Zarejestruj się tutaj.",
        "already_have_account_link": "Posiadasz już konto? Zaloguj się tutaj.",
        "username_validation": "Nazwa użytkownika musi mieć od 3 do 255 znaków oraz nie może zawierać spacji!",
        "username_validation2": "Nazwa użytkownika nie może zawierać następujących znaków: ' \" \\",
        "password_validation": "Hasło musi mieć od 8 do 255 znaków oraz nie może zawierać spacji!",
        "password_validation2": "Hasło nie może zawierać następujących znaków: ' \" \\",
        "website_validation": "Domena musi mieć od 5 do 255 znaków oraz nie może zawierać spacji!",
        "website_validation2": "Domena nie może zawierać następujących znaków: ' \" \\"
    },
    "cs": {
        "server": "Server",
        "website": "Web",
        "username": "Uživatelské jméno",
        "email": "E-mail",
        "password": "Heslo",
        "signin": "Přihlásit se",
        "signup": "Zaregistrovat se",
        "signout": "Odhlásit se",
        "okay": "OK",
        "add": "Přidat",
        "change": "Změnit",
        "use": "Použít",
        "copy": "Zkopírovat",
        "cancel": "Zrušit",
        "try_again": "Zkusit znovu",
        "success": "ÚSPĚCH",
        "error": "CHYBA",
        "delete": "Odstranit",
        "import": "Import",
        "import_from": "Importovat z {name}",
        "import_invalid": "Data ve vašem importu jsou neplatná!",
        "import_success": "{success_number} hesel úspěšně importováno!",
        "import_errors": "{success_number} hesel úspěšně importováno, ale {error_number} hesel NEBYLO importováno!",
        "backup": "Záloha",
        "export": "Export",
        "passwords": "Hesla",
        "import_export": "Import a export",
        "theme": "Téma",
        "search": "Hledat",
        "length": "Délka",
        "add_password": "Přidat heslo",
        "add_password_success": "Heslo bylo úspěšně přidáno",
        "change_password_success": "Heslo bylo úspěšně změněno",
        "remove_password_success": "Heslo bylo úspěšně odstraněno",
        "edit_password": "Změnit heslo",
        "password_generator": "Vygenerovat heslo",
        "delete_password": "Odstranit heslo",
        "delete_password_confirmation": "Opravdu chcete odstranit vaše heslo? Bude permanentně smazáno ze serveru. Tato akce je nevratná!",
        "delete_account": "Odstranit účet",
        "delete_account_info": "Jakmile odstraníte svůj účet, ztratíte všechna data, která k němu náleží.",
        "delete_account_confirmation": "Opravdu chcete odstranit váš účet? Všechna data budou permanentně smazána ze serveru. Tato akce je nevratná!",
        "url_invalid": "URL serveru je neplatná!",
        "server_unreachable": "Server je nedostupný!",
        "registration_completed": "Registrace dokončena!",
        "dont_have_account_link": "Ještě nemáte účet? Zaregistrujte se zde.",
        "already_have_account_link": "Již máte účet? Přihlaste se zde.",
        "username_validation": "Uživatelské jméno by mělo obsahovat 3 až 255 znaků a žádné mezery!",
        "username_validation2": "Uživatelské jméno nemůže obsahovat následující znaky: ' \" \\",
        "password_validation": "Heslo by mělo obsahovat 8 až 255 znaků a žádné mezery!",
        "password_validation2": "Heslo nemůže obsahovat následující znaky: ' \" \\",
        "website_validation": "Web by měl obsahovat 5 až 255 znaků a žádné mezery!",
        "website_validation2": "Web nemůže obsahovat následující znaky: ' \" \\"
    },
    "sv-SE": {
        "server": "Server",
        "website": "Hemsida",
        "username": "Användarnamn",
        "email": "E-post",
        "password": "Lösenord",
        "signin": "Logga in",
        "signup": "Bli Medlem",
        "signout": "Logga ut",
        "okay": "Okej",
        "add": "Lägg till",
        "change": "Ändra",
        "use": "Använd",
        "copy": "Kopiera",
        "cancel": "Avbryt",
        "try_again": "Försök igen",
        "success": "SUCCE",
        "error": "FEL",
        "delete": "Radera",
        "import": "Importera",
        "import_from": "Importera från {name}",
        "import_invalid": "Uppgifterna i din import är ogiltiga!",
        "import_success": "{success_number} lösenord importerade!",
        "import_errors": "{success_number} lösenord lösenord importerade, men {error_number} lösenord importerade inte!",
        "backup": "Säkerhetskopiering",
        "export": "Exportera",
        "passwords": "Lösenord",
        "import_export": "Importera & Exportera",
        "theme": "Tema",
        "search": "Sök",
        "length": "Längd",
        "add_password": "Lägg till lösenord",
        "add_password_success": "Lösenorden har raderats",
        "change_password_success": "Lösenordet har ändrats",
        "remove_password_success": "Lösenordet har tagits bort",
        "edit_password": "Ändra lösenord",
        "password_generator": "Generera lösenord",
        "delete_password": "Radera lösenord",
        "delete_password_confirmation": "Är du säker på att du vill radera ditt lösenord? Ditt lösenord vill bli permanent borttaget från denna servern. Denna åtgärden kan INTE göras ogjord.",
        "delete_account": "Radera konto",
        "delete_account_info": "När du har raderat ditt kontot, så kommer du förlora all data associerad med det.",
        "delete_account_confirmation": "Är du säker på att du vill radera ditt konto? All din data kommer att permanent raderas från servern. Denna åtgärden kan INTE göras ogjord.",
        "url_invalid": "Server url är ogiltig!",
        "server_unreachable": "Serven är onåbar!",
        "registration_completed": "Registreringen är klar!",
        "dont_have_account_link": "Har du inte ett konto än? Bli medlem här.",
        "already_have_account_link": "Är du redan en medlem? Logga in här.",
        "username_validation": "Användarnamnet bör vara mellan 3 och 255 karaktärer långt och can inte inehålla några mellanrum!",
        "username_validation2": "Användarnamnet kan inte inehålla dom följande karaktärerna: ' \" \\",
        "password_validation": "Användarnamnet bör vara från 8 till 255 karaktärer långt och can inte inehålla några mellanrum!",
        "password_validation2": "Lösenordet får inte inehålla angedda karaktärerna: ' \" \\",
        "website_validation": "Hemsidan bör vara från 5 till 255 karaktärer långt, och can inte inehålla några mellanrum!",
        "website_validation2": "Hemsidan kan inte inehålla de följande karaktärerna: ' \" \\"
    },
    "nl": {
        "server": "Server",
        "website": "Website",
        "username": "Gebruikersnaam",
        "email": "Email",
        "password": "Wachtwoord",
        "signin": "Inloggen",
        "signup": "Aanmelden",
        "signout": "Afmelden",
        "okay": "Ok",
        "add": "Toevoegen",
        "change": "Wijzigen",
        "use": "Gebruiken",
        "copy": "Kopiëren",
        "cancel": "Annuleren",
        "try_again": "Probeer opnieuw",
        "success": "Geslaagd",
        "error": "Foutmelding",
        "delete": "Verwijderen",
        "import": "Importeren",
        "import_from": "Importeren van {name}",
        "import_invalid": "Data import is ongeldig!",
        "import_success": "{success_number} wachtwoorden zijn succesvol geïmporteerd!",
        "import_errors": "{success_number} wachtwoorden zijn succesvol geimporteerd, {error_number} wachtworden zijn niet geïmporteerd!",
        "backup": "Backup",
        "export": "Exporteren",
        "passwords": "Wachtwoorden",
        "import_export": "Importeren & Exporteren",
        "theme": "Thema",
        "search": "Zoeken",
        "length": "Lengte",
        "add_password": "Wachtwoorden toevoegen",
        "add_password_success": "Wachtwoord succesvol toegevoegd",
        "change_password_success": "Wachtwoord succesvol gewijzigd",
        "remove_password_success": "Wachtwoord succesvol verwijderd",
        "edit_password": "Wachtwood bewerken",
        "password_generator": "Wachtwoorden Generator",
        "delete_password": "Wachtwoord verwijderen",
        "delete_password_confirmation": "Weet je het zeker dat je het wachtwoord wil verwijderen? Je wachtwoord wordt permanent verwijderd, dit kan niet ongedaan gemaakt worden.",
        "delete_account": "Verwijder account",
        "delete_account_info": "Je account verwijderd, alle gekoppelde data en wachtwoorden worden verwijderd.",
        "delete_account_confirmation": "Weet je zeker dat je je account wil verwijderen? Al je data wordt verwijderd. Deze actie kan niet ongedaan gemaakt worden!",
        "url_invalid": "Server url is ongeldig!",
        "server_unreachable": "Server is niet bereikbaar!",
        "registration_completed": "Registratie is voltooid!",
        "dont_have_account_link": "Nog geen account? Hier inschrijven.",
        "already_have_account_link": "Heb je al een account? Hier aanmelden.",
        "username_validation": "Gebruikersnaam moet minimaal 3 en maximaal 255 karakters zijn en mag geen spaties bevatten!",
        "username_validation2": "Gebruikersnaam kan niet de volgende speciale karakters bevatten: ' \" \\",
        "password_validation": "Wachtwoord moet minimaal 8 en maximaal 255 karakters zijn en mag geen spaties bevatten!",
        "password_validation2": "Wachtwoord kan niet de volgende speciale karakters bevatten: ' \" \\",
        "website_validation": "Website moet minimaal 5 en maximaal 255 karakters zijn en mag geen spaties bevatten!",
        "website_validation2": "Website kan niet de volgende speciale karakters bevatten: ' \" \\"
    },
    "sl": {
        "server": "Strežnik",
        "website": "Spletna stran",
        "username": "Uporabniško ime",
        "email": "E-naslov",
        "password": "Geslo",
        "signin": "Vpis",
        "signup": "Prijava",
        "signout": "Odjava",
        "okay": "Okay",
        "add": "Dodaj",
        "change": "Spremeni",
        "use": "Uporabi",
        "copy": "Kopiraj",
        "cancel": "Prekliči",
        "try_again": "Poskusite znova",
        "success": "USPEH",
        "error": "NAPAKA",
        "delete": "Izbriši",
        "import": "Uvozi",
        "import_from": "Uvozi iz {name}",
        "import_invalid": "Podatki pri uvozu so neveljavni!",
        "import_success": "{success_number} gesla so bila uspešno uvožena! ",
        "import_errors": "{success_number} gesel je bilo uspešno uvoženih, {error_number} gesel pa ni bilo uvoženih!",
        "backup": "Rezerva",
        "export": "Izvoz",
        "passwords": "Gesla",
        "import_export": "Uvoz in Izvoz",
        "theme": "Tema",
        "search": "Iskanje",
        "length": "Dolžina",
        "add_password": "Dodaj geslo",
        "add_password_success": "Geslo je bilo uspešno dodano",
        "change_password_success": "Geslo je bilo uspešno spremenjeno",
        "remove_password_success": "Geslo je bilo uspešno odstranjeno",
        "edit_password": "Uredi geslo",
        "password_generator": "Generator gesel",
        "delete_password": "Izbriši geslo",
        "delete_password_confirmation": "Ali ste prepričani, da želite izbrisati geslo? Vaše geslo bo za vedno odstranjeno s strežnika. Tega dejanja ni mogoče razveljaviti.",
        "delete_account": "Izbriši račun",
        "delete_account_info": "Ko izbrišete račun, boste izgubili vse podatke, povezane z njim.",
        "delete_account_confirmation": "Ali ste prepričani, da želite izbrisati svoj račun? Vsi vaši podatki bodo za vedno odstranjeni s strežnika. Tega dejanja ni mogoče razveljaviti.",
        "url_invalid": "URL strežnika ni veljaven!",
        "server_unreachable": "Strežnik je nedosegljiv!",
        "registration_completed": "Registracija je končana!",
        "dont_have_account_link": "Še nimate računa? Prijavite se tukaj.",
        "already_have_account_link": "Že imate račun? Prijavite se tukaj.",
        "username_validation": "Uporabniško ime mora biti dolgo med 3 in 255 znaki in ne sme vsebovati presledkov!",
        "username_validation2": "Uporabniško ime ne more vsebovati predvidenih posebnih znakov: ' \" \\",
        "password_validation": "Geslo mora biti dolgo med 8 in 255 znaki in ne sme vsebovati presledkov!",
        "password_validation2": "Geslo ne more vsebovati predvidenih posebnih znakov: ' \" \\",
        "website_validation": "Spletno mesto mora biti dolgo med 5 in 255 znaki in ne sme vsebovati presledkov!",
        "website_validation2": "Spletno mesto ne more vsebovati predvidenih posebnih znakov: ' \" \\"
    },
    "bs": {
        "server": "Server",
        "website": "Web stranica",
        "username": "Korisničko ime",
        "email": "Email",
        "password": "Lozinka",
        "signin": "Prijava",
        "signup": "Registracija",
        "signout": "Odjava",
        "okay": "U redu",
        "add": "Dodaj",
        "change": "Promjena",
        "use": "Upotrebi",
        "copy": "Kopiraj",
        "cancel": "Odustani",
        "try_again": "Pokušaj ponovo",
        "success": "USPJEH",
        "error": "GREŠKA",
        "delete": "Izbriši",
        "import": "Uvoz",
        "import_from": "Uvoz iz {name}",
        "import_invalid": "Podaci u uvozu su nevaljani!",
        "import_success": "Lozinka za {success_number} je uspješno uvezena!",
        "import_errors": "Lozinke za {success_number} su uspješno uvezene, ali lozinke za {error_number} nisu uvezene!",
        "backup": "Sigurnosna kopija",
        "export": "Izvoz",
        "passwords": "Lozinke",
        "import_export": "Uvoz i izvoz",
        "theme": "Teme",
        "search": "Pretraži",
        "length": "Dužina",
        "add_password": "Dodaj lozinku",
        "add_password_success": "Lozinka je uspješno dodana",
        "change_password_success": "Lozinka je uspješno promijenjena",
        "remove_password_success": "Lozinka je uspješno uklonjena",
        "edit_password": "Uredi lozinku",
        "password_generator": "Generator lozinki",
        "delete_password": "Izbriši lozinku",
        "delete_password_confirmation": "Jeste li sigurni da želite izbrisati lozinku? Vaša lozinka će biti zauvijek uklonjena sa servera. Ova radnja se ne može poništiti.",
        "delete_account": "Obriši račun",
        "delete_account_info": "Jednom kada izbrišete svoj račun, izgubit ćete sve podatke povezane s njim.",
        "delete_account_confirmation": "Jeste li sigurni da želite izbrisati svoj račun? Svi će vaši podaci biti zauvijek uklonjeni sa servera. Ova radnja se ne može poništiti.",
        "url_invalid": "Server url is invalid!",
        "server_unreachable": "Server je nedostupan!",
        "registration_completed": "Registracija je završena!",
        "dont_have_account_link": "Još nemate račun? Registrirajte se ovdje.",
        "already_have_account_link": "Već imate račun? Prijavite se ovdje.",
        "username_validation": "Korisničko ime mora imati između 3 i 255 znakova i ne smije sadržavati razmake!",
        "username_validation2": "Korisničko ime ne može sadržavati posebne znakove: ' \" \\",
        "password_validation": "Lozinka mora imati između 8 i 255 znakova i ne smije sadržavati razmake!",
        "password_validation2": "Lozinka ne može sadržavati posebne znakove: ' \" \\",
        "website_validation": "Web stranica može biti dugačka između 5 i 255 znakova i ne može sadržavati razmake!",
        "website_validation2": "Web stranica ne može sadržavati posebne znakove: ' \" \\"
    },
    "ro": {
        "server": "Server",
        "website": "Website",
        "username": "Nume de utilizator",
        "email": "Email",
        "password": "Parola",
        "signin": "Conectare",
        "signup": "Înregistrare",
        "signout": "Deconectare",
        "okay": "Bine",
        "add": "Adăuga",
        "change": "Schimbă",
        "use": "Utilizează",
        "copy": "Copiază",
        "cancel": "Anulează",
        "try_again": "Încearcă din nou",
        "success": "SUCCES",
        "error": "EROARE",
        "delete": "Șterge",
        "import": "Importă",
        "import_from": "Importă din {name}",
        "import_invalid": "Datele din importul dvs. nu sunt valide!",
        "import_success": "{success_number} parole importate cu succes!",
        "import_errors": "{success_number} parole importate cu succes, dar {error_number} parole NU au fost importate!",
        "backup": "Backup",
        "export": "Exportă",
        "passwords": "Parole",
        "import_export": "Importă & Exportă",
        "theme": "Temă",
        "search": "Caută",
        "length": "Lungime",
        "add_password": "Adăugați o parolă",
        "add_password_success": "Parola a fost adăugată cu succes",
        "change_password_success": "Parola a fost schimbată cu succes",
        "remove_password_success": "Parola a fost eliminată cu succes",
        "edit_password": "Schimbați parola",
        "password_generator": "Generați parola",
        "delete_password": "Ștergeți parola",
        "delete_password_confirmation": "Sigur doriți să ștergeți parola? Parola dvs. va fi eliminată definitiv de pe server. Această acțiune nu poate fi anulată.",
        "delete_account": "Șterge contul",
        "delete_account_info": "După ce vă ștergeți contul, veți pierde toate datele asociate acestuia.",
        "delete_account_confirmation": "Sigur doriți să vă ștergeți contul? Toate datele dvs. vor fi șterse definitiv de pe server. Această acțiune nu poate fi anulată.",
        "url_invalid": "Adresa url a serverului este nevalidă!",
        "server_unreachable": "Nu se poate accesa serverul!",
        "registration_completed": "Înregistrarea este finalizată!",
        "dont_have_account_link": "Nu aveți încă un cont? Înscrieți-vă aici.",
        "already_have_account_link": "Deja înregistrat? Conectați-vă aici.",
        "username_validation": "Numele de utilizator trebuie să aibă între 3 și 255 de caractere și nu poate conține spații!",
        "username_validation2": "Numele de utilizator nu poate conține următoarele caractere speciale: ' \" \\",
        "password_validation": "Parola trebuie să aibă între 8 și 255 de caractere și nu poate conține spații!",
        "password_validation2": "Parola nu poate conține următoarele caractere speciale: ' \" \\",
        "website_validation": "Adresa site-ului web trebuie să aibă între 5 și 255 de caractere și nu trebuie să aibă spații!",
        "website_validation2": "Adresa site-ului web nu poate conține următoarele caractere speciale: ' \" \\"
    }
}

const errors = {
    "en": {
        "0": "Successful",
        "1": "Username is invalid!",
        "2": "Password is incorrect!",
        "3": "Something went wrong while uploading data to the database!",
        "4": "Username is already registered!",
        "5": "Password must be 8 to 255 characters long, have at least one letter, one number and one special character!",
        "6": "Email is invalid!",
        "7": "Username does not exist!",
        "8": "You don't have any saved password.",
        "9": "Domain is invalid!",
        "10": "User does not own this password!",
        "11": "Something went wrong while deleting data from database!",
        "12": "Username must be 6 to 30 characters long, and may only contain letters, numbers and dots!",
        "13": "Something went wrong while updating data in database!",
        "14": "Json is invalid!",
        "15": "This server cannot accept more users!",
        "16": "You have reached the maximum amount of stored passwords!",
        "400": "Action was not provided in POST!",
        "401": "Action is invalid!",
        "403": "You didn't provide all required values in POST.",
        "404": "Can't connect into API.",
        "429": "You are sending too many requests! Please wait before executing this action again.",
        "505": "Something went wrong while connecting to the database!",
        "999": "You do NOT have permission to use this endpoint."
    },
    "zh-CN": {
        "0": "成功",
        "1": "用户名不合法！",
        "2": "密码不正确！",
        "3": "上传数据到数据库时发生了未知错误！",
        "4": "该用户名已经被注册!",
        "5": "密码长度需要至少8位，至少需要一个字母，一个数字，和一个特殊符号！",
        "6": "邮箱不合法！",
        "7": "用户名不存在！",
        "8": "你没有任何保存的密码！",
        "9": "域名不合法！",
        "10": "用户未拥有这个密码！",
        "11": "从数据库中删除数据时发生了错误！",
        "12": "用户名必须至少6位长度，并且只能包含字母，数字，和点！",
        "13": "更新数据库中数据时发生了错误！",
        "14": "Json不合法！",
        "15": "该服务器不接受更多用户！",
        "16": "你已达到最大存储密码数量！",
        "400": "你在POST中没有提供Action",
        "401": "操作不合法！",
        "403": "你在POST中没有提供所有所需的值",
        "404": "无法连接到API！",
        "429": "你发送了太多请求！请稍后再试！",
        "505": "连接数据库时出现错误！",
        "999": "你没有权限使用这个端点"
    },
    "hi": {
        "0": "सफल",
        "1": "उपयोगकर्ता नाम गलत",
        "2": "पासवर्ड गलत है",
        "3": "डेटाबेस में डेटा अपलोड करते समय कुछ गलत हुआ!",
        "4": "प्रयोक्ता का नाम पहले से पंजीकृत है!",
        "5": "पासवर्ड 8 से 255 वर्णों का होना चाहिए, कम से कम एक अक्षर, एक संख्या और एक विशेष वर्ण होना चाहिए!",
        "6": "ईमेल अमान्य है!",
        "7": "उपयोगकर्ता नाम मौजूद नहीं है!",
        "8": "आपके पास कोई सहेजा हुआ पासवर्ड नहीं है।",
        "9": "डोमेन अमान्य है!",
        "10": "उपयोगकर्ता के पास यह पासवर्ड नहीं है!",
        "11": "डेटाबेस से डेटा हटाते समय कुछ गलत हुआ!",
        "12": "उपयोगकर्ता नाम 6 से 30 वर्ण लंबा होना चाहिए, और इसमें केवल अक्षर, संख्याएं और बिंदु हो सकते हैं!",
        "13": "डेटाबेस में डेटा अपडेट करते समय कुछ गलत हुआ!",
        "14": "JSON अमान्य है!",
        "15": "यह सर्वर अधिक उपयोगकर्ताओं को स्वीकार नहीं कर सकता!",
        "16": "आप संग्रहीत पासवर्ड की अधिकतम मात्रा तक पहुंच गए हैं!",
        "400": "POST में कार्रवाई प्रदान नहीं की गई थी!",
        "401": "कार्रवाई अमान्य है!",
        "403": "आपने POST में सभी आवश्यक मान प्रदान नहीं किए हैं।",
        "404": "एपीआई में कनेक्ट नहीं हो सकता।",
        "429": "आप बहुत अधिक अनुरोध भेज रहे हैं! कृपया इस क्रिया को फिर से निष्पादित करने से पहले प्रतीक्षा करें।",
        "505": "डेटाबेस से कनेक्ट करते समय कुछ गलत हुआ!",
        "999": "आपको इस समापन बिंदु का उपयोग करने की अनुमति नहीं है।",
    },
    "fr": {
        "0": "Réussite",
        "1": "Le nom d'utilisateur est invalide !",
        "2": "Mot de passe incorrect !",
        "3": "Quelque chose s'est mal passé lors de l'upload des données en base de données !",
        "4": "Votre nom d'utilisateur est déjà enregistré!",
        "5": "Le mot de passe doit faire de 8 à 255 caractères, et contenir au moins une lettre, un nombre et un caractère spécial !",
        "6": "Email invalide !",
        "7": "Ce pseudo n'existe pas !",
        "8": "Vous n'avez pas de mots de passe enregistrés.",
        "9": "Domaine invalide !",
        "10": "L'utilisateur n'est pas le propriétaire du mot de passe !",
        "11": "Quelque chose s'est mal passé lors de la suppression des données en base de données !",
        "12": "Les pseudos doivent faire de 6 à 30 caractères, et ne doivent contenir que des lettres, des chiffres et des points !",
        "13": "Quelque chose s'est mal passé lors de la mise à jour des données en base de données !",
        "14": "Json invalide !",
        "15": "Ce serveur ne peut plus accepter d'utilisateurs !",
        "16": "Vous avez atteint le maximum de mots de passe enregistrés !",
        "400": "La requête n'a pas été fournie en POST !",
        "401": "Action invalide !",
        "403": "Vous n'avez pas fourni toutes les valeurs requises en POST.",
        "404": "Connection à l'API impossible.",
        "429": "Vous envoyez trop de requêtes ! Attendez avant de recommencer cette action.",
        "505": "Quelque chose s'est mal passé lors de la connection à la base de données !",
        "999": "Vous n'avez PAS la permission d'utiliser ce endpoint."
    },
    "ru": {
        "0": "Успешно",
        "1": "Имя пользователя недействительно!",
        "2": "Неверный пароль!",
        "3": "Что-то пошло не так при загрузке данных!",
        "4": "Имя пользователя уже зарегистрировано!",
        "5": "Пароль должен содержать от 8 до 255 символов, и содержать как минимум одну букву, цифру и символ!",
        "6": "Электронная почта недействительна!",
        "7": "Имя пользователя не существует!",
        "8": "У вас нет сохраненного пароля.",
        "9": "Домен недействителен!",
        "10": "У игрока другой пароль!",
        "11": "Что-то пошло не так при удалении данных!",
        "12": "Имя должно содержать от 6 до 30 символов и может содержать только буквы, цифры и точки!",
        "13": "Что-то пошло не так при обновлении данных!",
        "14": "Json недействителен!",
        "15": "Этот сервер не может принимать больше пользователей!",
        "16": "Вы достигли максимального количества сохраненных паролей!",
        "400": "Действие не было предоставлено в посте!",
        "401": "Действие недействительно!",
        "403": "Вы не предоставили все необходимые значения в пост.",
        "404": "Невозможно подключиться к API.",
        "429": "Вы отправляете слишком много запросов! Подождите, прежде чем выполнять это действие снова.",
        "505": "Что-то пошло не так при подключении к базе данных!",
        "999": "У вас нет прав."
    },
    "de": {
        "0": "Erfolgreich",
        "1": "Benutzername ist ungültig!",
        "2": "Passwort ist falsch!",
        "3": "Beim Einfügen von Daten in die Datenbank ist etwas schief gelaufen!",
        "4": "Benutzername ist bereits registriert!",
        "5": "Passwort muss zwischen 8 und 255 Zeichen lang sein und mindestens einen Buchstaben, eine Zahl und ein Sonderzeichen enthalten!",
        "6": "E-Mail ist ungültig!",
        "7": "Benutzername existiert nicht!",
        "8": "Sie haben kein gespeichertes Passwort.",
        "9": "Domain ist ungültig!",
        "10": "Benutzer besitzt dieses Passwort nicht!",
        "11": "Beim Löschen der Daten aus der Datenbank ist ein Fehler aufgetreten!",
        "12": "Der Benutzername muss zwischen 6 und 30 Zeichen lang sein und darf nur Buchstaben, Zahlen und Punkte enthalten!",
        "13": "Beim Aktualisieren der Daten in der Datenbank ist etwas schief gelaufen!",
        "14": "Json ist ungültig!",
        "15": "Dieser Server kann keine weiteren Benutzer akzeptieren!",
        "16": "Sie haben die maximale Anzahl gespeicherter Passwörter erreicht!",
        "400": "Aktion wurde im POST nicht bereitgestellt!",
        "401": "Aktion ist ungültig!",
        "403": "Sie haben nicht alle erforderlichen Werte im POST angegeben.",
        "404": "Kann keine Verbindung zur API herstellen.",
        "429": "Sie senden zu viele Anfragen! Bitte warten Sie einige Zeit, bevor Sie diese Aktion ausführen.",
        "505": "Beim Verbinden mit der Datenbank ist etwas schief gelaufen!",
        "999": "Sie sind nicht berechtigt, diesen Endpunkt zu verwenden."
    },
    "it": {
        "0": "Operazione completata",
        "1": "Nome utente non valido!",
        "2": "Password errata!",
        "3": "Qualcosa è andato storto durante il salvataggio dei dati nel database!",
        "4": "Nome utente già in uso!",
        "5": "La password deve essere compresa tra gli 8 e i 255 caratteri e deve contenere almeno una lettera, un numero e un carattere speciale!",
        "6": "Email non valida!",
        "7": "Il nome utente non esiste!",
        "8": "Non hai password salvate.",
        "9": "Dominio non valido!",
        "10": "L'utente non possiede questa password!",
        "11": "Qualcosa è andato storto durante l'eliminazione dei dati dal database!",
        "12": "Il nome utente deve essere compreso tra i 6 e i 30 caratteri e può contenere soltanto lettere, numeri e punti fermi ('.')!",
        "13": "Qualcosa è andato storto durante l'aggiornamento dei dati nel database!",
        "14": "Json non valido!",
        "15": "Questo server non può registrare altri utenti!",
        "16": "Hai raggiunto il numero massimo di password salvate!",
        "400": "Non è stata fornita alcuna azione in POST!",
        "401": "Azione non valida!",
        "403": "Non hai fornito tutti i valori richiesti in POST.",
        "404": "Impossibile connettersi all'API.",
        "429": "Stai mandando troppe richieste! Per favore aspetta prima di eseguire di nuovo questa azione.",
        "505": "Qualcosa è andato storto durante la connessione al database!",
        "999": "NON hai i permessi per utilizzare questo terminale."
    },
    "pl": {
        "0": "Sukces",
        "1": "Nieprawidłowa nazwa użytkownika!",
        "2": "Nieprawidłowe hasło!",
        "3": "Coś poszło nie tak podczas przesyłania danych!",
        "4": "Ta nazwa użytkownika jest już zajęta!",
        "5": "Hasło musi mieć od 8 do 255 znaków, posiadać co najmniej jedną literę, jedną cyfrę oraz jeden znak specjalny!",
        "6": "Nieprawidłowy adres e-mail!",
        "7": "Ta nazwa użytkownika nie istnieje!",
        "8": "Nie posiadasz żadnych zapisanych haseł.",
        "9": "Nieprawidłowa domena!",
        "10": "Użytkownik nie posiada tego hasła!",
        "11": "Coś poszło nie tak podczas usuwania danych!",
        "12": "Nazwa użytkownika musi mieć od 6 do 30 znaków oraz może zawierać jedynie litery, cyfry i kropki!",
        "13": "Coś poszło nie tak podczas aktualizowania danych!",
        "14": "Nieprawidłowy JSON!",
        "15": "Ten serwer nie może przyjąć więcej użytkowników!",
        "16": "Osiągnięto maksymalną liczbę zapisanych haseł!",
        "400": "Akcja nie została zawarta w POST!",
        "401": "Nieprawidłowa akcja!",
        "403": "Nie podano wszystkich wymaganych wartości w POST.",
        "404": "Nie można połączyć się z API.",
        "429": "Wysyłasz zbyt wiele żądań! Zaczekaj przed wykonaniem tej akcji ponownie.",
        "505": "Coś poszło nie tak podczas łączenia się z bazą danych!",
        "999": "Nie masz uprawnień do używania tego punktu końcowego."
    },
    "cs": {
        "0": "Úspěšné",
        "1": "Uživatelské jméno je neplatné!",
        "2": "Heslo je neplatné!",
        "3": "Při nahrávání dat do databáze se něco pokazilo!",
        "4": "Uživatelské jméno je již zaregistrováno!",
        "5": "Heslo musí být dlouhé 8 až 255 znaků, obsahovat alespoň jedno písmeno, jedno číslo a jeden speciální znak!",
        "6": "E-mail je neplatný!",
        "7": "Uživatelské jméno je neplatné!",
        "8": "Nemáte žádná uložená hesla.",
        "9": "Doména je neplatná!",
        "10": "Uživatel nevlastní toto heslo!",
        "11": "Při mazání dat z databáze se vyskytla chyba!",
        "12": "Uživatelské jméno musí být dlouhé 6 až 30 znaků a může obsahovat pouze písmena, čísla a tečky!",
        "13": "Při nahrávání dat do databáze se vyskytla chyba!",
        "14": "JSON je neplatný!",
        "15": "Tento server již nepřijímá další uživatele!",
        "16": "Dosáhli jste maximálního počtu uložených hesel!",
        "400": "Akce nebyla poskytnuta v POST!",
        "401": "Akce je neplatná!",
        "403": "Neposkytli jste všechna vyžadovaná data v POST.",
        "404": "Nepodařilo se připojit k API.",
        "429": "Posíláte příliš mnoho žádostí! Vyčkejte prosím před opětovným vykonáním této akce.",
        "505": "Při připojování se k databázi se vyskytla chyba!",
        "999": "Nemáte oprávnění k použití tohoto endpointu."
    },
    "sv-SE": {
        "0": "Framgångsrik",
        "1": "Användar namnet är felaktigt!",
        "2": "Lösenordet är korrekt!",
        "3": "Något gick fel medans du laddade upp data till databasen!",
        "4": "Användarnamnet är redan regristerat!",
        "5": "Lösenordet måste vara mellan 8 och 255 karaktärer långt, använd åtminstånde en bokstav, ett nummer och en special karaktär!",
        "6": "E-postaddressen är felaktig!",
        "7": "Användarnamnet finns inte!",
        "8": "Du har inget sparat lösenord.",
        "9": "Domänen är felaktig!",
        "10": "Användaren äger inte detta lösenordet!",
        "11": "Något gick fel medan vi raderade data från databasen!",
        "12": "Användernamnet måste vara mellan 6 och 30 karaktärer långt och får bara inehålla bokstäver, nummer, och punkter!",
        "13": "Något gick fel under uppdateringen av datan i databasen!",
        "14": "Json är ogiltig!",
        "15": "Denna servern kan inte acceptera fler användare!",
        "16": "Du har uppnått det maximala antalet lagrade lösenord!",
        "400": "Åtgärd tillhandahölls inte i POST!",
        "401": "Åtgärden är ogiltig!",
        "403": "Du angav inte alla nödvändiga värden i POST.",
        "404": "Kan inte ansluta till API.",
        "429": "Du skickar för måna förfrågningar! Vänta innan du utför den här åtgärden igen.",
        "505": "Något gick fel medans vi anslöt till databasen!",
        "999": "Du har INTE tillåtelse att använda den här slutpunkten."
    },
    "nl": {
        "0": "Voltooid",
        "1": "Gebruikersnaam is ongeldig!",
        "2": "Wachtwoord is ongeldig!",
        "3": "Er is iets fout gegaan bij het schrijven naar de database!",
        "4": "Gebruikersnaam is al in gebruik!",
        "5": "Gebruikersnaam moet minimaal 8 en maximaal 255 karakters zijn, minimaal één letter, één cijfer en één speciaal karakter bevatten!",
        "6": "Email is ongeldig!",
        "7": "Gebruikersnaam bestaat niet!",
        "8": "Er is geen wachtwoord opgeslagen.",
        "9": "Domein is ongeldig!",
        "10": "Gebruiker heeft dit wachtwoord niet!",
        "11": "Er is iets fout gegaan bij het verwijderen uit de database!",
        "12": "Gebruikersnaam moet minimaal 6 en maximaal 30 karakters zijn en kan alleen letters, nummers en punten bevatten!",
        "13": "Er is iets fout gegaan bij het bijwerken van de database!",
        "14": "Json is ongeldig!",
        "15": "De server heeft het maximale aantal gebruikers bereikt!",
        "16": "Je hebt het maximale aantal wachtwoorden bereikt!",
        "400": "Actie was niet aangegeven in POST!",
        "401": "Actie is ongeldig!",
        "403": "Je hebt niet alle verplicte velden ingevuld in POST.",
        "404": "Kan niet verbinden met API.",
        "429": "Je stuurt teveel verzoeken! Wacht even voor het uitvoeren van deze actie.",
        "505": "Er ging iets fout bij het verbinden met de database!",
        "999": "Je hebt geen rechten om te verbinden met dit eindpunt."
    },
    "sl": {
        "0": "Uspešno",
        "1": "Uporabniško ime je neveljavno!",
        "2": "Geslo je napačno!",
        "3": "Med vstavljanjem podatkov v bazo podatkov je prišlo do napake!",
        "4": "Uporabniško ime je že registrirano!",
        "5": "Geslo mora biti dolgo med 8 in 255 znaki in mora vsebovati vsaj eno črko, eno številko in en poseben znak!",
        "6": "E-pošta je neveljavna!",
        "7": "Uporabniško ime ne obstaja!",
        "8": "Nimate shranjenega gesla.",
        "9": "Domena je neveljavna!",
        "10": "Uporabnik ni lastnik tega gesla!",
        "11": "Med brisanjem podatkov iz baze podatkov je prišlo do napake!",
        "12": "Uporabniško ime mora biti dolgo med 6 in 30 znakov in lahko vsebuje samo črke, številke in pike!",
        "13": "Med posodabljanjem podatkov v bazi je prišlo do napake!",
        "14": "Json je neveljaven!",
        "15": "Ta strežnik ne more sprejeti več uporabnikov!",
        "16": "Dosegli ste največjo količino shranjenih gesel!",
        "400": "Akcija ni bila zagotovljena v POST-u!",
        "401": "Dejanje je neveljavno!",
        "403": "V POST niste navedli vseh zahtevanih vrednosti. ",
        "404": "Ne morem se povezati z API-jem.",
        "429": "Pošiljate preveč zahtev! Počakajte nekaj časa, preden izvedete to dejanje. ",
        "505": "Med povezovanjem z bazo podatkov je prišlo do napake!",
        "999": "Nimate dovoljenja za uporabo te točke."
    },
    "bs": {
        "0": "Uspješno",
        "1": "Korisničko ime je nevažeće!",
        "2": "Lozinka je netačna!",
        "3": "Nešto je naopako prilikom umetanja podataka u bazu podataka!",
        "4": "Korisničko ime je već registrovano!",
        "5": "Lozinka mora imati između 8 i 255 znakova i mora sadržavati najmanje jedno slovo, jedan broj i jedan specijalni znak!",
        "6": "Email adresa je nevažeća!",
        "7": "Korisničko ime ne postoji!",
        "8": "You don't have any saved password.",
        "9": "Domena je nevaljana!",
        "10": "Korisnik nije vlasnik ove lozinke!",
        "11": "Nešto je pošlo naopako prilikom brisanja podataka iz baze podataka!",
        "12": "Korisničko ime mora imati između 6 i 30 znakova i može sadržavati samo slova, brojeve i tačke!",
        "13": "Nešto je pošlo naopako prilikom ažuriranja podataka u bazi podataka!",
        "14": "Json je nevaljan!",
        "15": "Ovaj poslužitelj ne može prihvatiti više korisnika!",
        "16": "Dosegli ste maksimalnu količinu sačuvanih lozinki!",
        "400": "Akcija nije osigurana u POST-u!",
        "401": "Akcija je nevažeća!",
        "403": "Niste naveli sve potrebne vrijednosti u POST-u.",
        "404": "Ne može se povezati na API.",
        "429": "You are sending too many requests! Please wait some time before executing this action.",
        "505": "Nešto je pošlo naopako prilikom povezivanja na bazu podataka!",
        "999": "Nemate dozvolu za upotrebu ovog endpointa."
    },
    "ro": {
        "0": "Reușit",
        "1": "Numele de utilizator nu este valid!",
        "2": "Parola este incorectă!",
        "3": "A apărut o eroare la încărcarea datelor în baza de date!",
        "4": "Numele de utilizator este deja înregistrat!",
        "5": "Parola trebuie să aibă între 8 și 255 de caractere, să conțină cel puțin o literă, un număr și un caracter special!",
        "6": "Adresa de e-mail este invalida!",
        "7": "Numele de utilizator nu există!",
        "8": "Nu aveți nicio parolă salvată.",
        "9": "Domeniul nu este valid!",
        "10": "Utilizatorul nu deține această parolă!",
        "11": "A apărut o eroare la ștergerea datelor din baza de date!",
        "12": "Numele de utilizator trebuie să aibă 6 - 30 de caractere și poate conține doar litere, cifre și puncte!",
        "13": "A apărut o eroare la actualizarea datelor din baza de date!",
        "14": "Json-ul nu este valid!",
        "15": "Acest server nu poate accepta mai mulți utilizatori!",
        "16": "Ați atins numărul maxim de parole stocate!",
        "400": "Acțiunea nu a fost furnizată în POST!",
        "401": "Acțiunea nu este validă!",
        "403": "Nu ați furnizat toate valorile necesare în POST.",
        "404": "Nu se poate conecta la API.",
        "429": "Trimiteți prea multe solicitări! Vă rugăm să așteptați înainte de a executa din nou această acțiune.",
        "505": "A apărut o eroare la conectarea la baza de date!",
        "999": "NU aveți permisiunea de a utiliza acest endpoint."
    }
}
