const lang = {
    "en": {
        "server": "Server",
        "website": "Website",
        "username": "Username",
        "email": "Email",
        "password": "Password",
        "signin": "Sign in",
        "signup": "Sign up",
        "signout": "Sign out",
        "okay": "Okay",
        "add": "Add",
        "change": "Change",
        "use": "Use",
        "copy": "Copy",
        "cancel": "Cancel",
        "try_again": "Try again",
        "success": "SUCCESS",
        "error": "ERROR",
        "delete": "Delete",
        "import": "Import",
        "import_from": "Import from {name}",
        "import_invalid": "The data in your import is invalid!",
        "import_success": "{success_number} passwords imported successfully!",
        "import_errors": "{success_number} passwords imported successfully, but {error_number} passwords NOT imported!",
        "backup": "Backup",
        "export": "Export",
        "passwords": "Passwords",
        "import_export": "Import & Export",
        "theme": "Theme",
        "search": "Search",
        "length": "Length",
        "add_password": "Add password",
        "add_password_success": "Password has been added successfully",
        "change_password_success": "Password has been changed successfully",
        "remove_password_success": "Password has been removed successfully",
        "edit_password": "Change password",
        "password_generator": "Generate password",
        "delete_password": "Delete password",
        "delete_password_confirmation": "Are you sure you want to delete your password? Your password will be permanently removed from the server. This action can NOT be undone.",
        "delete_account": "Delete account",
        "delete_account_info": "Once you delete your account, you will lose all data associated with it.",
        "delete_account_confirmation": "Are you sure you want to delete your account? All of your data will be permanently removed from the server. This action can NOT be undone.",
        "url_invalid": "Server url is invalid!",
        "server_unreachable": "Server is unreachable!",
        "registration_completed": "Registration is completed!",
        "dont_have_account_link": "Don't have an account yet? Sign up here.",
        "already_have_account_link": "Already registered? Sign in here.",
        "username_validation": "Username should be between 3 to 255 characters long and can not contain any spaces!",
        "username_validation2": "Username may not contain the following special characters: ' \" \\",
        "password_validation": "Password should be from 8 to 255 characters long and can not contain any spaces!",
        "password_validation2": "Password may not contain provided special characters: ' \" \\",
        "website_validation": "Website should be from 5 to 255 characters long, and must not have any spaces!",
        "website_validation2": "Website may not contain the following special characters: ' \" \\"
    },
    "cs": {
        "server": "Server",
        "website": "Web",
        "username": "Uživatelské jméno",
        "email": "E-mail",
        "password": "Heslo",
        "signin": "Přihlásit se",
        "signup": "Zaregistrovat se",
        "signout": "Odhlásit se",
        "okay": "OK",
        "add": "Přidat",
        "change": "Změnit",
        "use": "Použít",
        "copy": "Zkopírovat",
        "cancel": "Zrušit",
        "try_again": "Zkusit znovu",
        "success": "ÚSPĚCH",
        "error": "CHYBA",
        "delete": "Odstranit",
        "import": "Import",
        "import_from": "Importovat z {name}",
        "import_invalid": "Data ve vašem importu jsou neplatná!",
        "import_success": "{success_number} hesel úspěšně importováno!",
        "import_errors": "{success_number} hesel úspěšně importováno, ale {error_number} hesel NEBYLO importováno!",
        "backup": "Záloha",
        "export": "Export",
        "passwords": "Hesla",
        "import_export": "Import a export",
        "theme": "Téma",
        "search": "Hledat",
        "length": "Délka",
        "add_password": "Přidat heslo",
        "add_password_success": "Heslo bylo úspěšně přidáno",
        "change_password_success": "Heslo bylo úspěšně změněno",
        "remove_password_success": "Heslo bylo úspěšně odstraněno",
        "edit_password": "Změnit heslo",
        "password_generator": "Vygenerovat heslo",
        "delete_password": "Odstranit heslo",
        "delete_password_confirmation": "Opravdu chcete odstranit vaše heslo? Bude permanentně smazáno ze serveru. Tato akce je nevratná!",
        "delete_account": "Odstranit účet",
        "delete_account_info": "Jakmile odstraníte svůj účet, ztratíte všechna data, která k němu náleží.",
        "delete_account_confirmation": "Opravdu chcete odstranit váš účet? Všechna data budou permanentně smazána ze serveru. Tato akce je nevratná!",
        "url_invalid": "URL serveru je neplatná!",
        "server_unreachable": "Server je nedostupný!",
        "registration_completed": "Registrace dokončena!",
        "dont_have_account_link": "Ještě nemáte účet? Zaregistrujte se zde.",
        "already_have_account_link": "Již máte účet? Přihlaste se zde.",
        "username_validation": "Uživatelské jméno by mělo obsahovat 3 až 255 znaků a žádné mezery!",
        "username_validation2": "Uživatelské jméno nemůže obsahovat následující znaky: ' \" \\",
        "password_validation": "Heslo by mělo obsahovat 8 až 255 znaků a žádné mezery!",
        "password_validation2": "Heslo nemůže obsahovat následující znaky: ' \" \\",
        "website_validation": "Web by měl obsahovat 5 až 255 znaků a žádné mezery!",
        "website_validation2": "Web nemůže obsahovat následující znaky: ' \" \\"
    },
    "de": {
        "server": "Server",
        "website": "Webseite",
        "username": "Nutzername",
        "email": "Email",
        "password": "Passwort",
        "signin": "Anmelden",
        "signup": "Anmelden",
        "signout": "Abmelden",
        "okay": "Okay",
        "add": "Hinzufügen",
        "change": "änderung",
        "use": "benutzen",
        "copy": "Kopieren",
        "cancel": "Abbrechen",
        "try_again": "Versuchen Sie es erneut",
        "success": "ERFOLG",
        "error": "FEHLER",
        "delete": "Löschen",
        "import": "Importieren",
        "import_from": "Importieren von {name}",
        "import_invalid": "Daten beim Import sind ungültig!",
        "import_success": "{success_number} passwörter wurden erfolgreich importiert!",
        "import_errors": "{success_number} passwörter wurden erfolgreich importiert, aber {error_number} Passwörter wurden nicht importiert!",
        "backup": "Backup",
        "export": "Exportieren",
        "passwords": "Passwörter",
        "import_export": "Import & Export",
        "theme": "Thema",
        "search": "Suche",
        "length": "Länge",
        "add_password": "Passwort hinzufügen",
        "add_password_success": "Passwort wurde erfolgreich hinzugefügt",
        "change_password_success": "Passwort wurde erfolgreich geändert",
        "remove_password_success": "Passwort wurde erfolgreich entfernt",
        "edit_password": "Passwort bearbeiten",
        "password_generator": "Passwort Generator",
        "delete_password": "Passwort löschen",
        "delete_password_confirmation": "Sind Sie sicher, dass Sie Ihr Passwort löschen möchten? Ihr Passwort wird für immer vom Server entfernt. Diese Aktion kann nicht rückgängig gemacht werden.",
        "delete_account": "Konto löschen",
        "delete_account_info": "Sobald Sie Ihr Konto löschen, verlieren Sie alle damit verbundenen Daten.",
        "delete_account_confirmation": "Sind Sie sicher, dass Sie Ihr Konto löschen möchten? Alle Ihre Daten werden für immer vom Server entfernt. Diese Aktion kann nicht rückgängig gemacht werden.",
        "url_invalid": "Server-URL ist ungültig!",
        "server_unreachable": "Server ist nicht erreichbar!",
        "registration_completed": "Registrierung ist abgeschlossen!",
        "dont_have_account_link": "Sie haben noch kein Konto? Melden Sie sich hier an.",
        "already_have_account_link": "Sie haben bereits ein Konto? Melden Sie sich hier an.",
        "username_validation": "Der Benutzername muss zwischen 3 und 255 Zeichen lang sein und darf keine Leerzeichen enthalten!",
        "username_validation2": "Benutzername darf keine angegebenen Sonderzeichen enthalten: ' \" \\",
        "password_validation": "Passwort muss zwischen 8 und 255 Zeichen lang sein und darf keine Leerzeichen enthalten!",
        "password_validation2": "Passwort darf keine angegebenen Sonderzeichen enthalten: ' \" \\",
        "website_validation": "Website kann zwischen 5 und 255 Zeichen lang sein und darf keine Leerzeichen enthalten!",
        "website_validation2": "Website darf keine angegebenen Sonderzeichen enthalten: ' \" \\"
    },
    "nl": {
        "server": "Server",
        "website": "Website",
        "username": "Gebruikersnaam",
        "email": "Email",
        "password": "Wachtwoord",
        "signin": "Inloggen",
        "signup": "Aanmelden",
        "signout": "Afmelden",
        "okay": "Ok",
        "add": "Toevoegen",
        "change": "Wijzigen",
        "use": "Gebruiken",
        "copy": "Kopiëren",
        "cancel": "Annuleren",
        "try_again": "Probeer opnieuw",
        "success": "Geslaagd",
        "error": "Foutmelding",
        "delete": "Verwijderen",
        "import": "Importeren",
        "import_from": "Importeren van {name}",
        "import_invalid": "Data import is ongeldig!",
        "import_success": "{success_number} wachtwoorden zijn succesvol geïmporteerd!",
        "import_errors": "{success_number} wachtwoorden zijn succesvol geimporteerd, {error_number} wachtworden zijn niet geïmporteerd!",
        "backup": "Backup",
        "export": "Exporteren",
        "passwords": "Wachtwoorden",
        "import_export": "Importeren & Exporteren",
        "theme": "Thema",
        "search": "Zoeken",
        "length": "Lengte",
        "add_password": "Wachtwoorden toevoegen",
        "add_password_success": "Wachtwoord succesvol toegevoegd",
        "change_password_success": "Wachtwoord succesvol gewijzigd",
        "remove_password_success": "Wachtwoord succesvol verwijderd",
        "edit_password": "Wachtwood bewerken",
        "password_generator": "Wachtwoorden Generator",
        "delete_password": "Wachtwoord verwijderen",
        "delete_password_confirmation": "Weet je het zeker dat je het wachtwoord wil verwijderen? Je wachtwoord wordt permanent verwijderd, dit kan niet ongedaan gemaakt worden.",
        "delete_account": "Verwijder account",
        "delete_account_info": "Je account verwijderd, alle gekoppelde data en wachtwoorden worden verwijderd.",
        "delete_account_confirmation": "Weet je zeker dat je je account wil verwijderen? Al je data wordt verwijderd. Deze actie kan niet ongedaan gemaakt worden!",
        "url_invalid": "Server url is ongeldig!",
        "server_unreachable": "Server is niet bereikbaar!",
        "registration_completed": "Registratie is voltooid!",
        "dont_have_account_link": "Nog geen account? Hier inschrijven.",
        "already_have_account_link": "Heb je al een account? Hier aanmelden.",
        "username_validation": "Gebruikersnaam moet minimaal 3 en maximaal 255 karakters zijn en mag geen spaties bevatten!",
        "username_validation2": "Gebruikersnaam kan niet de volgende speciale karakters bevatten: ' \" \\",
        "password_validation": "Wachtwoord moet minimaal 8 en maximaal 255 karakters zijn en mag geen spaties bevatten!",
        "password_validation2": "Wachtwoord kan niet de volgende speciale karakters bevatten: ' \" \\",
        "website_validation": "Website moet minimaal 5 en maximaal 255 karakters zijn en mag geen spaties bevatten!",
        "website_validation2": "Website kan niet de volgende speciale karakters bevatten: ' \" \\"
    },
    "sl": {
        "server": "Strežnik",
        "website": "Spletna stran",
        "username": "Uporabniško ime",
        "email": "E-naslov",
        "password": "Geslo",
        "signin": "Vpis",
        "signup": "Prijava",
        "signout": "Odjava",
        "okay": "Okay",
        "add": "Dodaj",
        "change": "Spremeni",
        "use": "Uporabi",
        "copy": "Kopiraj",
        "cancel": "Prekliči",
        "try_again": "Poskusite znova",
        "success": "USPEH",
        "error": "NAPAKA",
        "delete": "Izbriši",
        "import": "Uvozi",
        "import_from": "Uvozi iz {name}",
        "import_invalid": "Podatki pri uvozu so neveljavni!",
        "import_success": "{success_number} gesla so bila uspešno uvožena! ",
        "import_errors": "{success_number} gesel je bilo uspešno uvoženih, {error_number} gesel pa ni bilo uvoženih!",
        "backup": "Rezerva",
        "export": "Izvoz",
        "passwords": "Gesla",
        "import_export": "Uvoz in Izvoz",
        "theme": "Tema",
        "search": "Iskanje",
        "length": "Dolžina",
        "add_password": "Dodaj geslo",
        "add_password_success": "Geslo je bilo uspešno dodano",
        "change_password_success": "Geslo je bilo uspešno spremenjeno",
        "remove_password_success": "Geslo je bilo uspešno odstranjeno",
        "edit_password": "Uredi geslo",
        "password_generator": "Generator gesel",
        "delete_password": "Izbriši geslo",
        "delete_password_confirmation": "Ali ste prepričani, da želite izbrisati geslo? Vaše geslo bo za vedno odstranjeno s strežnika. Tega dejanja ni mogoče razveljaviti.",
        "delete_account": "Izbriši račun",
        "delete_account_info": "Ko izbrišete račun, boste izgubili vse podatke, povezane z njim.",
        "delete_account_confirmation": "Ali ste prepričani, da želite izbrisati svoj račun? Vsi vaši podatki bodo za vedno odstranjeni s strežnika. Tega dejanja ni mogoče razveljaviti.",
        "url_invalid": "URL strežnika ni veljaven!",
        "server_unreachable": "Strežnik je nedosegljiv!",
        "registration_completed": "Registracija je končana!",
        "dont_have_account_link": "Še nimate računa? Prijavite se tukaj.",
        "already_have_account_link": "Že imate račun? Prijavite se tukaj.",
        "username_validation": "Uporabniško ime mora biti dolgo med 3 in 255 znaki in ne sme vsebovati presledkov!",
        "username_validation2": "Uporabniško ime ne more vsebovati predvidenih posebnih znakov: ' \" \\",
        "password_validation": "Geslo mora biti dolgo med 8 in 255 znaki in ne sme vsebovati presledkov!",
        "password_validation2": "Geslo ne more vsebovati predvidenih posebnih znakov: ' \" \\",
        "website_validation": "Spletno mesto mora biti dolgo med 5 in 255 znaki in ne sme vsebovati presledkov!",
        "website_validation2": "Spletno mesto ne more vsebovati predvidenih posebnih znakov: ' \" \\"
    },
    "bs": {
        "server": "Server",
        "website": "Web stranica",
        "username": "Korisničko ime",
        "email": "Email",
        "password": "Lozinka",
        "signin": "Prijava",
        "signup": "Registracija",
        "signout": "Odjava",
        "okay": "U redu",
        "add": "Dodaj",
        "change": "Promjena",
        "use": "Upotrebi",
        "copy": "Kopiraj",
        "cancel": "Odustani",
        "try_again": "Pokušaj ponovo",
        "success": "USPJEH",
        "error": "GREŠKA",
        "delete": "Izbriši",
        "import": "Uvoz",
        "import_from": "Uvoz iz {name}",
        "import_invalid": "Podaci u uvozu su nevaljani!",
        "import_success": "Lozinka za {success_number} je uspješno uvezena!",
        "import_errors": "Lozinke za {success_number} su uspješno uvezene, ali lozinke za {error_number} nisu uvezene!",
        "backup": "Sigurnosna kopija",
        "export": "Izvoz",
        "passwords": "Lozinke",
        "import_export": "Uvoz i izvoz",
        "theme": "Teme",
        "search": "Pretraži",
        "length": "Dužina",
        "add_password": "Dodaj lozinku",
        "add_password_success": "Lozinka je uspješno dodana",
        "change_password_success": "Lozinka je uspješno promijenjena",
        "remove_password_success": "Lozinka je uspješno uklonjena",
        "edit_password": "Uredi lozinku",
        "password_generator": "Generator lozinki",
        "delete_password": "Izbriši lozinku",
        "delete_password_confirmation": "Jeste li sigurni da želite izbrisati lozinku? Vaša lozinka će biti zauvijek uklonjena sa servera. Ova radnja se ne može poništiti.",
        "delete_account": "Obriši račun",
        "delete_account_info": "Jednom kada izbrišete svoj račun, izgubit ćete sve podatke povezane s njim.",
        "delete_account_confirmation": "Jeste li sigurni da želite izbrisati svoj račun? Svi će vaši podaci biti zauvijek uklonjeni sa servera. Ova radnja se ne može poništiti.",
        "url_invalid": "Server url is invalid!",
        "server_unreachable": "Server je nedostupan",
        "registration_completed": "Registracija je završena!",
        "dont_have_account_link": "Još nemate račun? Registrirajte se ovdje.",
        "already_have_account_link": "Već imate račun? Prijavite se ovdje.",
        "username_validation": "Korisničko ime mora imati između 3 i 255 znakova i ne smije sadržavati razmake!",
        "username_validation2": "Korisničko ime ne može sadržavati posebne znakove: ' \" \\",
        "password_validation": "Lozinka mora imati između 8 i 255 znakova i ne smije sadržavati razmake!",
        "password_validation2": "Lozinka ne može sadržavati posebne znakove: ' \" \\",
        "website_validation": "Web stranica može biti dugačka između 5 i 255 znakova i ne može sadržavati razmake!",
        "website_validation2": "Web stranica ne može sadržavati posebne znakove: ' \" \\"
    }
}

const errors = {
    "en": {
        "0": "Successful",
        "1": "Username is invalid!",
        "2": "Password is incorrect!",
        "3": "Something went wrong while uploading data to the database!",
        "4": "Username is already registered!",
        "5": "Password must be 8 to 255 characters long, have at least one letter, one number and one special character!",
        "6": "Email is invalid!",
        "7": "Username does not exist!",
        "8": "You don't have any saved password.",
        "9": "Domain is invalid!",
        "10": "User does not own this password!",
        "11": "Something went wrong while deleting data from database!",
        "12": "Username must be 6 to 30 characters long, and may only contain letters, numbers and dots!",
        "13": "Something went wrong while updating data in database!",
        "14": "Json is invalid!",
        "15": "This server cannot accept more users!",
        "16": "You have reached the maximum amount of stored passwords!",
        "400": "Action was not provided in POST!",
        "401": "Action is invalid!",
        "403": "You didn't provide all required values in POST.",
        "404": "Can't connect into API.",
        "429": "You are sending too many requests! Please wait before executing this action again.",
        "505": "Something went wrong while connecting to the database!",
        "999": "You do NOT have permission to use this endpoint."
    },
    "de": {
        "0": "Erfolgreich",
        "1": "Benutzername ist ungültig!",
        "2": "Passwort ist falsch!",
        "3": "Beim Einfügen von Daten in die Datenbank ist etwas schief gelaufen!",
        "4": "Benutzername ist bereits registriert!",
        "5": "Passwort muss zwischen 8 und 255 Zeichen lang sein und mindestens einen Buchstaben, eine Zahl und ein Sonderzeichen enthalten!",
        "6": "E-Mail ist ungültig!",
        "7": "Benutzername existiert nicht!",
        "8": "Sie haben kein gespeichertes Passwort.",
        "9": "Domain ist ungültig!",
        "10": "Benutzer besitzt dieses Passwort nicht!",
        "11": "Beim Löschen der Daten aus der Datenbank ist ein Fehler aufgetreten!",
        "12": "Der Benutzername muss zwischen 6 und 30 Zeichen lang sein und darf nur Buchstaben, Zahlen und Punkte enthalten!",
        "13": "Beim Aktualisieren der Daten in der Datenbank ist etwas schief gelaufen!",
        "14": "Json ist ungültig!",
        "15": "Dieser Server kann keine weiteren Benutzer akzeptieren!",
        "16": "Sie haben die maximale Anzahl gespeicherter Passwörter erreicht!",
        "400": "Aktion wurde im POST nicht bereitgestellt!",
        "401": "Aktion ist ungültig!",
        "403": "Sie haben nicht alle erforderlichen Werte im POST angegeben.",
        "404": "Kann keine Verbindung zur API herstellen.",
        "429": "Sie senden zu viele Anfragen! Bitte warten Sie einige Zeit, bevor Sie diese Aktion ausführen.",
        "505": "Beim Verbinden mit der Datenbank ist etwas schief gelaufen!",
        "999": "Sie sind nicht berechtigt, diesen Endpunkt zu verwenden."
    },
    "nl": {
        "0": "Voltooid",
        "1": "Gebruikersnaam is ongeldig!",
        "2": "Wachtwoord is ongeldig!",
        "3": "Er is iets fout gegaan bij het schrijven naar de database!",
        "4": "Gebruikersnaam is al in gebruik!",
        "5": "Gebruikersnaam moet minimaal 8 en maximaal 255 karakters zijn, minimaal één letter, één cijfer en één speciaal karakter bevatten!",
        "6": "Email is ongeldig!",
        "7": "Gebruikersnaam bestaat niet!",
        "8": "Er is geen wachtwoord opgeslagen.",
        "9": "Domein is ongeldig!",
        "10": "Gebruiker heeft dit wachtwoord niet!",
        "11": "Er is iets fout gegaan bij het verwijderen uit de database!",
        "12": "Gebruikersnaam moet minimaal 6 en maximaal 30 karakters zijn en kan alleen letters, nummers en punten bevatten!",
        "13": "Er is iets fout gegaan bij het bijwerken van de database!",
        "14": "Json is ongeldig!",
        "15": "De server heeft het maximale aantal gebruikers bereikt!",
        "16": "Je hebt het maximale aantal wachtwoorden bereikt!",
        "400": "Actie was niet aangegeven in POST!",
        "401": "Actie is ongeldig!",
        "403": "Je hebt niet alle verplicte velden ingevuld in POST.",
        "404": "Kan niet verbinden met API.",
        "429": "Je stuurt teveel verzoeken! Wacht even voor het uitvoeren van deze actie.",
        "505": "Er ging iets fout bij het verbinden met de database!",
        "999": "Je hebt geen rechten om te verbinden met dit eindpunt."
    },
    "sl": {
        "0": "Uspešno",
        "1": "Uporabniško ime je neveljavno!",
        "2": "Geslo je napačno!",
        "3": "Med vstavljanjem podatkov v bazo podatkov je prišlo do napake!",
        "4": "Uporabniško ime je že registrirano!",
        "5": "Geslo mora biti dolgo med 8 in 255 znaki in mora vsebovati vsaj eno črko, eno številko in en poseben znak!",
        "6": "E-pošta je neveljavna!",
        "7": "Uporabniško ime ne obstaja!",
        "8": "Nimate shranjenega gesla.",
        "9": "Domena je neveljavna!",
        "10": "Uporabnik ni lastnik tega gesla!",
        "11": "Med brisanjem podatkov iz baze podatkov je prišlo do napake!",
        "12": "Uporabniško ime mora biti dolgo med 6 in 30 znakov in lahko vsebuje samo črke, številke in pike!",
        "13": "Med posodabljanjem podatkov v bazi je prišlo do napake!",
        "14": "Json je neveljaven!",
        "15": "Ta strežnik ne more sprejeti več uporabnikov!",
        "16": "Dosegli ste največjo količino shranjenih gesel!",
        "400": "Akcija ni bila zagotovljena v POST-u!",
        "401": "Dejanje je neveljavno!",
        "403": "V POST niste navedli vseh zahtevanih vrednosti. ",
        "404": "Ne morem se povezati z API-jem.",
        "429": "Pošiljate preveč zahtev! Počakajte nekaj časa, preden izvedete to dejanje. ",
        "505": "Med povezovanjem z bazo podatkov je prišlo do napake!",
        "999": "Nimate dovoljenja za uporabo te točke."
    },
    "bs": {
        "0": "Uspješno", 
        "1": "Korisničko ime je nevažeće!",
        "2": "Lozinka je netačna!",
        "3": "Nešto je naopako prilikom umetanja podataka u bazu podataka!",
        "4": "Korisničko ime je već registrovano",
        "5": "Lozinka mora imati između 8 i 255 znakova i mora sadržavati najmanje jedno slovo, jedan broj i jedan specijalni znak!",
        "6": "Email adresa je nevažeća!",
        "7": "Korisničko ime ne postoji!",
        "8": "You don't have any saved password.",
        "9": "Domena je nevaljana!",
        "10": "Korisnik nije vlasnik ove lozinke!",
        "11": "Nešto je pošlo naopako prilikom brisanja podataka iz baze podataka!",
        "12": "Korisničko ime mora imati između 6 i 30 znakova i može sadržavati samo slova, brojeve i tačke!",
        "13": "Nešto je pošlo naopako prilikom ažuriranja podataka u bazi podataka!",
        "14": "Json je nevaljan!",
        "15": "Ovaj poslužitelj ne može prihvatiti više korisnika!",
        "16": "Dosegli ste maksimalnu količinu sačuvanih lozinki",
        "400": "Akcija nije osigurana u POST-u!",
        "401": "Akcija je nevažeća!",
        "403": "Niste naveli sve potrebne vrijednosti u POST-u.",
        "404": "Ne može se povezati na API",
        "429": "You are sending too many requests! Please wait some time before executing this action.",
        "505": "Nešto je pošlo naopako prilikom povezivanja na bazu podataka!",
        "999": "Nemate dozvolu za upotrebu ovog endpointa."
    }
}
